// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY5rn9xYxyk_n33o7bV45XGlb8iLzzrg4',
    appId: '1:993229612670:web:045893b582a4d669ae9a2f',
    messagingSenderId: '993229612670',
    projectId: 'education-app-e40f4',
    authDomain: 'education-app-e40f4.firebaseapp.com',
    storageBucket: 'education-app-e40f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt8LrHsN7BFYVH8lObw7tmaKflSzagEKA',
    appId: '1:993229612670:android:21ff2d78e73d1226ae9a2f',
    messagingSenderId: '993229612670',
    projectId: 'education-app-e40f4',
    storageBucket: 'education-app-e40f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjONYlJBB6DQ0eZ1F6SdWZDHs1CF4mmx0',
    appId: '1:993229612670:ios:9b44f10f4c71c61bae9a2f',
    messagingSenderId: '993229612670',
    projectId: 'education-app-e40f4',
    storageBucket: 'education-app-e40f4.appspot.com',
    iosBundleId: 'com.example.educationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjONYlJBB6DQ0eZ1F6SdWZDHs1CF4mmx0',
    appId: '1:993229612670:ios:bfd7d6797fd3b24fae9a2f',
    messagingSenderId: '993229612670',
    projectId: 'education-app-e40f4',
    storageBucket: 'education-app-e40f4.appspot.com',
    iosBundleId: 'com.example.educationProject.RunnerTests',
  );
}
